### PR TITLE
Add NODE_TLS_REJECT_UNAUTHORIZED to npm configuration

### LINKED ISSUE #21: DEPTH_ZERO_SELF_SIGNED_CERT error
Same commands as #20, but a different error

With this shell script I get a DEPTH_ZERO_SELF_SIGNED_CERT error

```sh
npm config set proxy http://192.168.1.1:7288/
npm config set https-proxy http://192.168.1.1:7288/
npm config set strict-ssl false
npm install windshaft
```

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
node-pre-gyp http DEPTH_ZERO_SELF_SIGNED_CERT (falling back to source compile with node-gyp)

```

I'm running npm-proxy-cache from source with `
./bin/npm-proxy-cache -h 192.168.1.1 -p 7288 -t 7200` on another machine.

### PR DESCRIPTION
**Pull request by pnorman**
Fixes #21

### CODE REVIEW

**Comment by runk** [comment]
Hmm. What's the difference in https://github.com/runk/npm-proxy-cache/blob/master/lib/proxy.js#L13? It should work the same way, right

**Comment by pnorman** [comment]
That line runs on the `npm-proxy-server`, what I added changes where `npm` is running. The SSL validation errors aren't coming from npm-proxy-server, but from npm.

npm-proxy-server should be validating SSL, since to do otherwise would leave it open to a MITM between it and upstream.

**Comment by runk** [comment]
Ah. Makes sense. I thought npm-proxy-cache is unhappy.

Can we say something like 

```
If you're experiencing errors about `DEPTH_ZERO_SELF_SIGNED_CERT` you might want to do `export NODE_TLS_REJECT_UNAUTHORIZED=0` in your terminal. For more information check https://github.com/request/request/issues/418 discussion.
```

**Comment by pnorman** [comment]
That would work too. I don't know what triggers the error since you're not getting it.

One thought is that it's because I'm connecting to 192.168.1.1 rather than localhost, it does different checks.

If so, then a message could be printed when starting with a non-default IP.

**Comment by runk** [comment]
Archiving for now

**Pull request closed without merging**
